name: Construir y lanzar

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 #se lanza en la maquina virual de Ubu
      
    - name: Install Node.js  #le instalamos node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build #coge y compila en la carpeta dist
    
    - name: Generate 404.html
      run: |
        repo_name=$(git rev-parse --show-toplevel | xargs basename)
        echo "<!DOCTYPE html><html lang="es"><head><meta http-equiv='refresh' content='0; url=https://angelegar2015.github.io/clase_Pablo/'></head></html>" > dist/404.html

      


    - name: Deploy to GitHub Pages #donde queremos que se mueva
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages 
        folder: dist #es todo el proyecto pero lo compila para que esto  lo pueda leer

